// AUTO-GENERATED

#ifndef _GI_GOBJECT__CONSTANTS_HPP_
#define _GI_GOBJECT__CONSTANTS_HPP_

namespace gi {

namespace repository {

namespace GObject {

const gint PARAM_MASK_ = G_PARAM_MASK;

const gint PARAM_STATIC_STRINGS_ = G_PARAM_STATIC_STRINGS;

const gint PARAM_USER_SHIFT_ = G_PARAM_USER_SHIFT;

const gint SIGNAL_FLAGS_MASK_ = G_SIGNAL_FLAGS_MASK;

const gint SIGNAL_MATCH_MASK_ = G_SIGNAL_MATCH_MASK;

const GType TYPE_FLAG_RESERVED_ID_BIT_ = G_TYPE_FLAG_RESERVED_ID_BIT;

const gint TYPE_FUNDAMENTAL_MAX_ = G_TYPE_FUNDAMENTAL_MAX;

const gint TYPE_FUNDAMENTAL_SHIFT_ = G_TYPE_FUNDAMENTAL_SHIFT;

const gint TYPE_RESERVED_BSE_FIRST_ = G_TYPE_RESERVED_BSE_FIRST;

const gint TYPE_RESERVED_BSE_LAST_ = G_TYPE_RESERVED_BSE_LAST;

const gint TYPE_RESERVED_GLIB_FIRST_ = G_TYPE_RESERVED_GLIB_FIRST;

const gint TYPE_RESERVED_GLIB_LAST_ = G_TYPE_RESERVED_GLIB_LAST;

const gint TYPE_RESERVED_USER_FIRST_ = G_TYPE_RESERVED_USER_FIRST;

const gint VALUE_COLLECT_FORMAT_MAX_LENGTH_ = G_VALUE_COLLECT_FORMAT_MAX_LENGTH;

const gint VALUE_INTERNED_STRING_ = G_VALUE_INTERNED_STRING;

const gint VALUE_NOCOPY_CONTENTS_ = G_VALUE_NOCOPY_CONTENTS;

} // namespace GObject

} // namespace repository

} // namespace gi

#endif
