// AUTO-GENERATED

#ifndef _GI_GLIB__CONSTANTS_HPP_
#define _GI_GLIB__CONSTANTS_HPP_

namespace gi {

namespace repository {

namespace GLib {

const gint ALLOCATOR_LIST_ = G_ALLOCATOR_LIST;

const gint ALLOCATOR_NODE_ = G_ALLOCATOR_NODE;

const gint ALLOCATOR_SLIST_ = G_ALLOCATOR_SLIST;

const gint ALLOC_AND_FREE_ = G_ALLOC_AND_FREE;

const gint ALLOC_ONLY_ = G_ALLOC_ONLY;

const gint ANALYZER_ANALYZING_ = G_ANALYZER_ANALYZING;

const gint ASCII_DTOSTR_BUF_SIZE_ = G_ASCII_DTOSTR_BUF_SIZE;

const gint ATOMIC_REF_COUNT_INIT_ = G_ATOMIC_REF_COUNT_INIT;

const gint BIG_ENDIAN_ = G_BIG_ENDIAN;

const gchar CSET_A_2_Z_[] = G_CSET_A_2_Z;

const gchar CSET_DIGITS_[] = G_CSET_DIGITS;

const gchar CSET_a_2_z[] = G_CSET_a_2_z;

const gint DATALIST_FLAGS_MASK_ = G_DATALIST_FLAGS_MASK;

const gint DATE_BAD_DAY_ = G_DATE_BAD_DAY;

const gint DATE_BAD_JULIAN_ = G_DATE_BAD_JULIAN;

const gint DATE_BAD_YEAR_ = G_DATE_BAD_YEAR;

const gint DIR_SEPARATOR_ = G_DIR_SEPARATOR;

const gchar DIR_SEPARATOR_S_[] = G_DIR_SEPARATOR_S;

const gdouble E_ = G_E;

const gchar GINT16_FORMAT_[] = G_GINT16_FORMAT;

const gchar GINT16_MODIFIER_[] = G_GINT16_MODIFIER;

const gchar GINT32_FORMAT_[] = G_GINT32_FORMAT;

const gchar GINT32_MODIFIER_[] = G_GINT32_MODIFIER;

const gchar GINT64_FORMAT_[] = G_GINT64_FORMAT;

const gchar GINT64_MODIFIER_[] = G_GINT64_MODIFIER;

const gchar GINTPTR_FORMAT_[] = G_GINTPTR_FORMAT;

const gchar GINTPTR_MODIFIER_[] = G_GINTPTR_MODIFIER;

const gchar GSIZE_FORMAT_[] = G_GSIZE_FORMAT;

const gchar GSIZE_MODIFIER_[] = G_GSIZE_MODIFIER;

const gchar GSSIZE_FORMAT_[] = G_GSSIZE_FORMAT;

const gchar GSSIZE_MODIFIER_[] = G_GSSIZE_MODIFIER;

const gchar GUINT16_FORMAT_[] = G_GUINT16_FORMAT;

const gchar GUINT32_FORMAT_[] = G_GUINT32_FORMAT;

const gchar GUINT64_FORMAT_[] = G_GUINT64_FORMAT;

const gchar GUINTPTR_FORMAT_[] = G_GUINTPTR_FORMAT;

const gint HAVE_GINT64_ = G_HAVE_GINT64;

const gint HAVE_GNUC_VARARGS_ = G_HAVE_GNUC_VARARGS;

const gint HAVE_GNUC_VISIBILITY_ = G_HAVE_GNUC_VISIBILITY;

const gint HAVE_GROWING_STACK_ = G_HAVE_GROWING_STACK;

const gint HAVE_ISO_VARARGS_ = G_HAVE_ISO_VARARGS;

const gint HOOK_FLAG_USER_SHIFT_ = G_HOOK_FLAG_USER_SHIFT;

const gint IEEE754_DOUBLE_BIAS_ = G_IEEE754_DOUBLE_BIAS;

const gint IEEE754_FLOAT_BIAS_ = G_IEEE754_FLOAT_BIAS;

const gchar KEY_FILE_DESKTOP_GROUP_[] = G_KEY_FILE_DESKTOP_GROUP;

const gchar KEY_FILE_DESKTOP_KEY_ACTIONS_[] = G_KEY_FILE_DESKTOP_KEY_ACTIONS;

const gchar KEY_FILE_DESKTOP_KEY_CATEGORIES_[] = G_KEY_FILE_DESKTOP_KEY_CATEGORIES;

const gchar KEY_FILE_DESKTOP_KEY_COMMENT_[] = G_KEY_FILE_DESKTOP_KEY_COMMENT;

const gchar KEY_FILE_DESKTOP_KEY_DBUS_ACTIVATABLE_[] = G_KEY_FILE_DESKTOP_KEY_DBUS_ACTIVATABLE;

const gchar KEY_FILE_DESKTOP_KEY_EXEC_[] = G_KEY_FILE_DESKTOP_KEY_EXEC;

const gchar KEY_FILE_DESKTOP_KEY_GENERIC_NAME_[] = G_KEY_FILE_DESKTOP_KEY_GENERIC_NAME;

const gchar KEY_FILE_DESKTOP_KEY_HIDDEN_[] = G_KEY_FILE_DESKTOP_KEY_HIDDEN;

const gchar KEY_FILE_DESKTOP_KEY_ICON_[] = G_KEY_FILE_DESKTOP_KEY_ICON;

const gchar KEY_FILE_DESKTOP_KEY_MIME_TYPE_[] = G_KEY_FILE_DESKTOP_KEY_MIME_TYPE;

const gchar KEY_FILE_DESKTOP_KEY_NAME_[] = G_KEY_FILE_DESKTOP_KEY_NAME;

const gchar KEY_FILE_DESKTOP_KEY_NOT_SHOW_IN_[] = G_KEY_FILE_DESKTOP_KEY_NOT_SHOW_IN;

const gchar KEY_FILE_DESKTOP_KEY_NO_DISPLAY_[] = G_KEY_FILE_DESKTOP_KEY_NO_DISPLAY;

const gchar KEY_FILE_DESKTOP_KEY_ONLY_SHOW_IN_[] = G_KEY_FILE_DESKTOP_KEY_ONLY_SHOW_IN;

const gchar KEY_FILE_DESKTOP_KEY_PATH_[] = G_KEY_FILE_DESKTOP_KEY_PATH;

const gchar KEY_FILE_DESKTOP_KEY_STARTUP_NOTIFY_[] = G_KEY_FILE_DESKTOP_KEY_STARTUP_NOTIFY;

const gchar KEY_FILE_DESKTOP_KEY_STARTUP_WM_CLASS_[] = G_KEY_FILE_DESKTOP_KEY_STARTUP_WM_CLASS;

const gchar KEY_FILE_DESKTOP_KEY_TERMINAL_[] = G_KEY_FILE_DESKTOP_KEY_TERMINAL;

const gchar KEY_FILE_DESKTOP_KEY_TRY_EXEC_[] = G_KEY_FILE_DESKTOP_KEY_TRY_EXEC;

const gchar KEY_FILE_DESKTOP_KEY_TYPE_[] = G_KEY_FILE_DESKTOP_KEY_TYPE;

const gchar KEY_FILE_DESKTOP_KEY_URL_[] = G_KEY_FILE_DESKTOP_KEY_URL;

const gchar KEY_FILE_DESKTOP_KEY_VERSION_[] = G_KEY_FILE_DESKTOP_KEY_VERSION;

const gchar KEY_FILE_DESKTOP_TYPE_APPLICATION_[] = G_KEY_FILE_DESKTOP_TYPE_APPLICATION;

const gchar KEY_FILE_DESKTOP_TYPE_DIRECTORY_[] = G_KEY_FILE_DESKTOP_TYPE_DIRECTORY;

const gchar KEY_FILE_DESKTOP_TYPE_LINK_[] = G_KEY_FILE_DESKTOP_TYPE_LINK;

const gint LITTLE_ENDIAN_ = G_LITTLE_ENDIAN;

const gdouble LN10_ = G_LN10;

const gdouble LN2_ = G_LN2;

const gdouble LOG_2_BASE_10_ = G_LOG_2_BASE_10;

const gint LOG_FATAL_MASK_ = G_LOG_FATAL_MASK;

const gint LOG_LEVEL_USER_SHIFT_ = G_LOG_LEVEL_USER_SHIFT;

const gint MAJOR_VERSION_ = GLIB_MAJOR_VERSION;

const gint16 MAXINT16_ = G_MAXINT16;

const gint32 MAXINT32_ = G_MAXINT32;

const gint64 MAXINT64_ = G_MAXINT64;

const gint8 MAXINT8_ = G_MAXINT8;

const guint16 MAXUINT16_ = G_MAXUINT16;

const guint32 MAXUINT32_ = G_MAXUINT32;

const guint64 MAXUINT64_ = G_MAXUINT64;

const guint8 MAXUINT8_ = G_MAXUINT8;

const gint MICRO_VERSION_ = GLIB_MICRO_VERSION;

const gint16 MININT16_ = G_MININT16;

const gint32 MININT32_ = G_MININT32;

const gint64 MININT64_ = G_MININT64;

const gint8 MININT8_ = G_MININT8;

const gint MINOR_VERSION_ = GLIB_MINOR_VERSION;

const gchar MODULE_SUFFIX_[] = G_MODULE_SUFFIX;

const gchar OPTION_REMAINING_[] = G_OPTION_REMAINING;

const gint PDP_ENDIAN_ = G_PDP_ENDIAN;

const gdouble PI_ = G_PI;

const gchar PID_FORMAT_[] = G_PID_FORMAT;

const gdouble PI_2_ = G_PI_2;

const gdouble PI_4_ = G_PI_4;

const gchar POLLFD_FORMAT_[] = G_POLLFD_FORMAT;

const gint PRIORITY_DEFAULT_ = G_PRIORITY_DEFAULT;

const gint PRIORITY_DEFAULT_IDLE_ = G_PRIORITY_DEFAULT_IDLE;

const gint PRIORITY_HIGH_ = G_PRIORITY_HIGH;

const gint PRIORITY_HIGH_IDLE_ = G_PRIORITY_HIGH_IDLE;

const gint PRIORITY_LOW_ = G_PRIORITY_LOW;

const gint REF_COUNT_INIT_ = G_REF_COUNT_INIT;

const gint SEARCHPATH_SEPARATOR_ = G_SEARCHPATH_SEPARATOR;

const gchar SEARCHPATH_SEPARATOR_S_[] = G_SEARCHPATH_SEPARATOR_S;

const gint SIZEOF_LONG_ = GLIB_SIZEOF_LONG;

const gint SIZEOF_SIZE_T_ = GLIB_SIZEOF_SIZE_T;

const gint SIZEOF_SSIZE_T_ = GLIB_SIZEOF_SSIZE_T;

const gint SIZEOF_VOID_P_ = GLIB_SIZEOF_VOID_P;

const gboolean SOURCE_CONTINUE_ = G_SOURCE_CONTINUE;

const gboolean SOURCE_REMOVE_ = G_SOURCE_REMOVE;

const gdouble SQRT2_ = G_SQRT2;

const gchar STR_DELIMITERS_[] = G_STR_DELIMITERS;

const gint SYSDEF_AF_INET_ = GLIB_SYSDEF_AF_INET;

const gint SYSDEF_AF_INET6_ = GLIB_SYSDEF_AF_INET6;

const gint SYSDEF_AF_UNIX_ = GLIB_SYSDEF_AF_UNIX;

const gint SYSDEF_MSG_DONTROUTE_ = GLIB_SYSDEF_MSG_DONTROUTE;

const gint SYSDEF_MSG_OOB_ = GLIB_SYSDEF_MSG_OOB;

const gint SYSDEF_MSG_PEEK_ = GLIB_SYSDEF_MSG_PEEK;

const gchar TEST_OPTION_ISOLATE_DIRS_[] = G_TEST_OPTION_ISOLATE_DIRS;

const gint64 TIME_SPAN_DAY_ = G_TIME_SPAN_DAY;

const gint64 TIME_SPAN_HOUR_ = G_TIME_SPAN_HOUR;

const gint64 TIME_SPAN_MILLISECOND_ = G_TIME_SPAN_MILLISECOND;

const gint64 TIME_SPAN_MINUTE_ = G_TIME_SPAN_MINUTE;

const gint64 TIME_SPAN_SECOND_ = G_TIME_SPAN_SECOND;

const gint UNICHAR_MAX_DECOMPOSITION_LENGTH_ = G_UNICHAR_MAX_DECOMPOSITION_LENGTH;

const gchar URI_RESERVED_CHARS_GENERIC_DELIMITERS_[] = G_URI_RESERVED_CHARS_GENERIC_DELIMITERS;

const gchar URI_RESERVED_CHARS_SUBCOMPONENT_DELIMITERS_[] = G_URI_RESERVED_CHARS_SUBCOMPONENT_DELIMITERS;

const gint USEC_PER_SEC_ = G_USEC_PER_SEC;

const gint VA_COPY_AS_ARRAY_ = G_VA_COPY_AS_ARRAY;

const gint VERSION_MIN_REQUIRED_ = GLIB_VERSION_MIN_REQUIRED;

} // namespace GLib

} // namespace repository

} // namespace gi

#endif
