// AUTO-GENERATED

#ifndef _GI_GIO_GIO_IMPL_HPP_
#define _GI_GIO_GIO_IMPL_HPP_

#include "gio.hpp"

GI_DISABLE_DEPRECATED_WARN_BEGIN

#ifdef GI_INCLUDE_IMPL_GIO_BEGIN
GI_INCLUDE_IMPL_GIO_BEGIN
#endif




#include "action_impl.hpp"
#include "actionentry_impl.hpp"
#include "actiongroup_impl.hpp"
#include "actionmap_impl.hpp"
#include "appinfo_impl.hpp"
#include "appinfomonitor_impl.hpp"
#include "applaunchcontext_impl.hpp"
#include "application_impl.hpp"
#include "applicationcommandline_impl.hpp"
#include "asyncinitable_impl.hpp"
#include "asyncresult_impl.hpp"
#include "bufferedinputstream_impl.hpp"
#include "bufferedoutputstream_impl.hpp"
#include "bytesicon_impl.hpp"
#include "cancellable_impl.hpp"
#include "charsetconverter_impl.hpp"
#include "converter_impl.hpp"
#include "converterinputstream_impl.hpp"
#include "converteroutputstream_impl.hpp"
#include "credentials_impl.hpp"
#include "datagrambased_impl.hpp"
#include "datainputstream_impl.hpp"
#include "dataoutputstream_impl.hpp"
#include "dbusactiongroup_impl.hpp"
#include "dbusannotationinfo_impl.hpp"
#include "dbusarginfo_impl.hpp"
#include "dbusauthobserver_impl.hpp"
#include "dbusconnection_impl.hpp"
#include "dbuserrorentry_impl.hpp"
#include "dbusinterface_impl.hpp"
#include "dbusinterfaceinfo_impl.hpp"
#include "dbusinterfaceskeleton_impl.hpp"
#include "dbusinterfacevtable_impl.hpp"
#include "dbusmenumodel_impl.hpp"
#include "dbusmessage_impl.hpp"
#include "dbusmethodinfo_impl.hpp"
#include "dbusmethodinvocation_impl.hpp"
#include "dbusnodeinfo_impl.hpp"
#include "dbusobject_impl.hpp"
#include "dbusobjectmanager_impl.hpp"
#include "dbusobjectmanagerclient_impl.hpp"
#include "dbusobjectmanagerserver_impl.hpp"
#include "dbusobjectproxy_impl.hpp"
#include "dbusobjectskeleton_impl.hpp"
#include "dbuspropertyinfo_impl.hpp"
#include "dbusproxy_impl.hpp"
#include "dbusserver_impl.hpp"
#include "dbussignalinfo_impl.hpp"
#include "dbussubtreevtable_impl.hpp"
#include "debugcontroller_impl.hpp"
#include "debugcontrollerdbus_impl.hpp"
#include "desktopappinfo_impl.hpp"
#include "drive_impl.hpp"
#include "dtlsclientconnection_impl.hpp"
#include "dtlsconnection_impl.hpp"
#include "dtlsserverconnection_impl.hpp"
#include "emblem_impl.hpp"
#include "emblemedicon_impl.hpp"
#include "file_impl.hpp"
#include "fileattributeinfo_impl.hpp"
#include "fileattributeinfolist_impl.hpp"
#include "fileattributematcher_impl.hpp"
#include "filedescriptorbased_impl.hpp"
#include "fileenumerator_impl.hpp"
#include "fileicon_impl.hpp"
#include "fileinfo_impl.hpp"
#include "fileinputstream_impl.hpp"
#include "fileiostream_impl.hpp"
#include "filemonitor_impl.hpp"
#include "filenamecompleter_impl.hpp"
#include "fileoutputstream_impl.hpp"
#include "filterinputstream_impl.hpp"
#include "filteroutputstream_impl.hpp"
#include "icon_impl.hpp"
#include "inetaddress_impl.hpp"
#include "inetaddressmask_impl.hpp"
#include "inetsocketaddress_impl.hpp"
#include "initable_impl.hpp"
#include "inputmessage_impl.hpp"
#include "inputstream_impl.hpp"
#include "inputvector_impl.hpp"
#include "iomodule_impl.hpp"
#include "iostream_impl.hpp"
#include "listmodel_impl.hpp"
#include "liststore_impl.hpp"
#include "loadableicon_impl.hpp"
#include "memoryinputstream_impl.hpp"
#include "memorymonitor_impl.hpp"
#include "memoryoutputstream_impl.hpp"
#include "menu_impl.hpp"
#include "menuattributeiter_impl.hpp"
#include "menuitem_impl.hpp"
#include "menulinkiter_impl.hpp"
#include "menumodel_impl.hpp"
#include "mount_impl.hpp"
#include "mountoperation_impl.hpp"
#include "nativesocketaddress_impl.hpp"
#include "nativevolumemonitor_impl.hpp"
#include "networkaddress_impl.hpp"
#include "networkmonitor_impl.hpp"
#include "networkservice_impl.hpp"
#include "notification_impl.hpp"
#include "outputmessage_impl.hpp"
#include "outputstream_impl.hpp"
#include "outputvector_impl.hpp"
#include "permission_impl.hpp"
#include "pollableinputstream_impl.hpp"
#include "pollableoutputstream_impl.hpp"
#include "powerprofilemonitor_impl.hpp"
#include "propertyaction_impl.hpp"
#include "proxy_impl.hpp"
#include "proxyaddress_impl.hpp"
#include "proxyaddressenumerator_impl.hpp"
#include "proxyresolver_impl.hpp"
#include "remoteactiongroup_impl.hpp"
#include "resolver_impl.hpp"
#include "resource_impl.hpp"
#include "seekable_impl.hpp"
#include "settings_impl.hpp"
#include "settingsbackend_impl.hpp"
#include "settingsschema_impl.hpp"
#include "settingsschemakey_impl.hpp"
#include "settingsschemasource_impl.hpp"
#include "simpleaction_impl.hpp"
#include "simpleactiongroup_impl.hpp"
#include "simpleasyncresult_impl.hpp"
#include "simpleiostream_impl.hpp"
#include "simplepermission_impl.hpp"
#include "simpleproxyresolver_impl.hpp"
#include "socket_impl.hpp"
#include "socketaddress_impl.hpp"
#include "socketaddressenumerator_impl.hpp"
#include "socketclient_impl.hpp"
#include "socketconnectable_impl.hpp"
#include "socketconnection_impl.hpp"
#include "socketcontrolmessage_impl.hpp"
#include "socketlistener_impl.hpp"
#include "socketservice_impl.hpp"
#include "srvtarget_impl.hpp"
#include "staticresource_impl.hpp"
#include "subprocess_impl.hpp"
#include "subprocesslauncher_impl.hpp"
#include "task_impl.hpp"
#include "tcpconnection_impl.hpp"
#include "tcpwrapperconnection_impl.hpp"
#include "testdbus_impl.hpp"
#include "themedicon_impl.hpp"
#include "threadedsocketservice_impl.hpp"
#include "tlsbackend_impl.hpp"
#include "tlscertificate_impl.hpp"
#include "tlsclientconnection_impl.hpp"
#include "tlsconnection_impl.hpp"
#include "tlsdatabase_impl.hpp"
#include "tlsfiledatabase_impl.hpp"
#include "tlsinteraction_impl.hpp"
#include "tlspassword_impl.hpp"
#include "tlsserverconnection_impl.hpp"
#include "unixconnection_impl.hpp"
#include "unixcredentialsmessage_impl.hpp"
#include "unixfdlist_impl.hpp"
#include "unixfdmessage_impl.hpp"
#include "unixinputstream_impl.hpp"
#include "unixmountentry_impl.hpp"
#include "unixmountmonitor_impl.hpp"
#include "unixmountpoint_impl.hpp"
#include "unixoutputstream_impl.hpp"
#include "unixsocketaddress_impl.hpp"
#include "vfs_impl.hpp"
#include "volume_impl.hpp"
#include "volumemonitor_impl.hpp"
#include "zlibcompressor_impl.hpp"
#include "zlibdecompressor_impl.hpp"

#include "_callbacks_impl.hpp"
#include "_functions_impl.hpp"


#if defined(__has_include)
#if __has_include(<gio/gio_extra_def_impl.hpp>)
#include <gio/gio_extra_def_impl.hpp>
#endif
#endif


#if defined(__has_include)
#if __has_include(<gio/gio_extra_impl.hpp>)
#include <gio/gio_extra_impl.hpp>
#endif
#endif


GI_DISABLE_DEPRECATED_WARN_BEGIN

#ifdef GI_INCLUDE_GIO_BEGIN
GI_INCLUDE_GIO_BEGIN
#endif

#endif
