// AUTO-GENERATED

#ifndef _GI_GTK__CONSTANTS_HPP_
#define _GI_GTK__CONSTANTS_HPP_

namespace gi {

namespace repository {

namespace Gtk {

const gint ACCESSIBLE_VALUE_UNDEFINED_ = GTK_ACCESSIBLE_VALUE_UNDEFINED;

const gint BINARY_AGE_ = GTK_BINARY_AGE;

const gint INPUT_ERROR_ = GTK_INPUT_ERROR;

const gint INTERFACE_AGE_ = GTK_INTERFACE_AGE;

const guint INVALID_LIST_POSITION_ = GTK_INVALID_LIST_POSITION;

const gchar LEVEL_BAR_OFFSET_FULL_[] = GTK_LEVEL_BAR_OFFSET_FULL;

const gchar LEVEL_BAR_OFFSET_HIGH_[] = GTK_LEVEL_BAR_OFFSET_HIGH;

const gchar LEVEL_BAR_OFFSET_LOW_[] = GTK_LEVEL_BAR_OFFSET_LOW;

const gint MAJOR_VERSION_ = GTK_MAJOR_VERSION;

const gint MAX_COMPOSE_LEN_ = GTK_MAX_COMPOSE_LEN;

const gchar MEDIA_FILE_EXTENSION_POINT_NAME_[] = GTK_MEDIA_FILE_EXTENSION_POINT_NAME;

const gint MICRO_VERSION_ = GTK_MICRO_VERSION;

const gint MINOR_VERSION_ = GTK_MINOR_VERSION;

const gchar PAPER_NAME_A3_[] = GTK_PAPER_NAME_A3;

const gchar PAPER_NAME_A4_[] = GTK_PAPER_NAME_A4;

const gchar PAPER_NAME_A5_[] = GTK_PAPER_NAME_A5;

const gchar PAPER_NAME_B5_[] = GTK_PAPER_NAME_B5;

const gchar PAPER_NAME_EXECUTIVE_[] = GTK_PAPER_NAME_EXECUTIVE;

const gchar PAPER_NAME_LEGAL_[] = GTK_PAPER_NAME_LEGAL;

const gchar PAPER_NAME_LETTER_[] = GTK_PAPER_NAME_LETTER;

const gchar PRINT_SETTINGS_COLLATE_[] = GTK_PRINT_SETTINGS_COLLATE;

const gchar PRINT_SETTINGS_DEFAULT_SOURCE_[] = GTK_PRINT_SETTINGS_DEFAULT_SOURCE;

const gchar PRINT_SETTINGS_DITHER_[] = GTK_PRINT_SETTINGS_DITHER;

const gchar PRINT_SETTINGS_DUPLEX_[] = GTK_PRINT_SETTINGS_DUPLEX;

const gchar PRINT_SETTINGS_FINISHINGS_[] = GTK_PRINT_SETTINGS_FINISHINGS;

const gchar PRINT_SETTINGS_MEDIA_TYPE_[] = GTK_PRINT_SETTINGS_MEDIA_TYPE;

const gchar PRINT_SETTINGS_NUMBER_UP_[] = GTK_PRINT_SETTINGS_NUMBER_UP;

const gchar PRINT_SETTINGS_NUMBER_UP_LAYOUT_[] = GTK_PRINT_SETTINGS_NUMBER_UP_LAYOUT;

const gchar PRINT_SETTINGS_N_COPIES_[] = GTK_PRINT_SETTINGS_N_COPIES;

const gchar PRINT_SETTINGS_ORIENTATION_[] = GTK_PRINT_SETTINGS_ORIENTATION;

const gchar PRINT_SETTINGS_OUTPUT_BASENAME_[] = GTK_PRINT_SETTINGS_OUTPUT_BASENAME;

const gchar PRINT_SETTINGS_OUTPUT_BIN_[] = GTK_PRINT_SETTINGS_OUTPUT_BIN;

const gchar PRINT_SETTINGS_OUTPUT_DIR_[] = GTK_PRINT_SETTINGS_OUTPUT_DIR;

const gchar PRINT_SETTINGS_OUTPUT_FILE_FORMAT_[] = GTK_PRINT_SETTINGS_OUTPUT_FILE_FORMAT;

const gchar PRINT_SETTINGS_OUTPUT_URI_[] = GTK_PRINT_SETTINGS_OUTPUT_URI;

const gchar PRINT_SETTINGS_PAGE_RANGES_[] = GTK_PRINT_SETTINGS_PAGE_RANGES;

const gchar PRINT_SETTINGS_PAGE_SET_[] = GTK_PRINT_SETTINGS_PAGE_SET;

const gchar PRINT_SETTINGS_PAPER_FORMAT_[] = GTK_PRINT_SETTINGS_PAPER_FORMAT;

const gchar PRINT_SETTINGS_PAPER_HEIGHT_[] = GTK_PRINT_SETTINGS_PAPER_HEIGHT;

const gchar PRINT_SETTINGS_PAPER_WIDTH_[] = GTK_PRINT_SETTINGS_PAPER_WIDTH;

const gchar PRINT_SETTINGS_PRINTER_[] = GTK_PRINT_SETTINGS_PRINTER;

const gchar PRINT_SETTINGS_PRINTER_LPI_[] = GTK_PRINT_SETTINGS_PRINTER_LPI;

const gchar PRINT_SETTINGS_PRINT_PAGES_[] = GTK_PRINT_SETTINGS_PRINT_PAGES;

const gchar PRINT_SETTINGS_QUALITY_[] = GTK_PRINT_SETTINGS_QUALITY;

const gchar PRINT_SETTINGS_RESOLUTION_[] = GTK_PRINT_SETTINGS_RESOLUTION;

const gchar PRINT_SETTINGS_RESOLUTION_X_[] = GTK_PRINT_SETTINGS_RESOLUTION_X;

const gchar PRINT_SETTINGS_RESOLUTION_Y_[] = GTK_PRINT_SETTINGS_RESOLUTION_Y;

const gchar PRINT_SETTINGS_REVERSE_[] = GTK_PRINT_SETTINGS_REVERSE;

const gchar PRINT_SETTINGS_SCALE_[] = GTK_PRINT_SETTINGS_SCALE;

const gchar PRINT_SETTINGS_USE_COLOR_[] = GTK_PRINT_SETTINGS_USE_COLOR;

const gchar PRINT_SETTINGS_WIN32_DRIVER_EXTRA_[] = GTK_PRINT_SETTINGS_WIN32_DRIVER_EXTRA;

const gchar PRINT_SETTINGS_WIN32_DRIVER_VERSION_[] = GTK_PRINT_SETTINGS_WIN32_DRIVER_VERSION;

const gint PRIORITY_RESIZE_ = GTK_PRIORITY_RESIZE;

const gint STYLE_PROVIDER_PRIORITY_APPLICATION_ = GTK_STYLE_PROVIDER_PRIORITY_APPLICATION;

const gint STYLE_PROVIDER_PRIORITY_FALLBACK_ = GTK_STYLE_PROVIDER_PRIORITY_FALLBACK;

const gint STYLE_PROVIDER_PRIORITY_SETTINGS_ = GTK_STYLE_PROVIDER_PRIORITY_SETTINGS;

const gint STYLE_PROVIDER_PRIORITY_THEME_ = GTK_STYLE_PROVIDER_PRIORITY_THEME;

const gint STYLE_PROVIDER_PRIORITY_USER_ = GTK_STYLE_PROVIDER_PRIORITY_USER;

const gint TEXT_VIEW_PRIORITY_VALIDATE_ = GTK_TEXT_VIEW_PRIORITY_VALIDATE;

const gint TREE_SORTABLE_DEFAULT_SORT_COLUMN_ID_ = GTK_TREE_SORTABLE_DEFAULT_SORT_COLUMN_ID;

const gint TREE_SORTABLE_UNSORTED_SORT_COLUMN_ID_ = GTK_TREE_SORTABLE_UNSORTED_SORT_COLUMN_ID;

} // namespace Gtk

} // namespace repository

} // namespace gi

#endif
