// AUTO-GENERATED

#ifndef _GI_GTK_GTK_HPP_
#define _GI_GTK_GTK_HPP_

#include <gi/gi.hpp>

#include <gdk/gdk.hpp>
#include <gsk/gsk.hpp>


#if defined(__has_include)
#if __has_include(<gtk/gtk_setup_pre_def.hpp>)
#include <gtk/gtk_setup_pre_def.hpp>
#endif
#endif


#if defined(__has_include)
#if __has_include(<gtk/gtk_setup_pre.hpp>)
#include <gtk/gtk_setup_pre.hpp>
#endif
#endif

#include <gtk/gtk.h>

#if defined(__has_include)
#if __has_include(<gtk/gtk_setup_post_def.hpp>)
#include <gtk/gtk_setup_post_def.hpp>
#endif
#endif


#if defined(__has_include)
#if __has_include(<gtk/gtk_setup_post.hpp>)
#include <gtk/gtk_setup_post.hpp>
#endif
#endif


GI_DISABLE_DEPRECATED_WARN_BEGIN

#ifdef GI_INCLUDE_GTK_BEGIN
GI_INCLUDE_GTK_BEGIN
#endif

#include "_types.hpp"
#include "_enums.hpp"
#include "_flags.hpp"
#include "_constants.hpp"
#include "_callbacks.hpp"


#include "aboutdialog.hpp"
#include "accessible.hpp"
#include "accessiblerange.hpp"
#include "actionable.hpp"
#include "actionbar.hpp"
#include "activateaction.hpp"
#include "adjustment.hpp"
#include "alertdialog.hpp"
#include "alternativetrigger.hpp"
#include "anyfilter.hpp"
#include "appchooser.hpp"
#include "appchooserbutton.hpp"
#include "appchooserdialog.hpp"
#include "appchooserwidget.hpp"
#include "application.hpp"
#include "applicationwindow.hpp"
#include "aspectframe.hpp"
#include "assistant.hpp"
#include "assistantpage.hpp"
#include "atcontext.hpp"
#include "binlayout.hpp"
#include "bitset.hpp"
#include "bitsetiter.hpp"
#include "bookmarklist.hpp"
#include "boolfilter.hpp"
#include "border.hpp"
#include "box.hpp"
#include "boxlayout.hpp"
#include "buildable.hpp"
#include "buildableparser.hpp"
#include "builder.hpp"
#include "buildercscope.hpp"
#include "builderlistitemfactory.hpp"
#include "builderscope.hpp"
#include "button.hpp"
#include "calendar.hpp"
#include "callbackaction.hpp"
#include "cellarea.hpp"
#include "cellareabox.hpp"
#include "cellareacontext.hpp"
#include "celleditable.hpp"
#include "celllayout.hpp"
#include "cellrenderer.hpp"
#include "cellrendereraccel.hpp"
#include "cellrenderercombo.hpp"
#include "cellrendererpixbuf.hpp"
#include "cellrendererprogress.hpp"
#include "cellrendererspin.hpp"
#include "cellrendererspinner.hpp"
#include "cellrenderertext.hpp"
#include "cellrenderertoggle.hpp"
#include "cellview.hpp"
#include "centerbox.hpp"
#include "centerlayout.hpp"
#include "checkbutton.hpp"
#include "colorbutton.hpp"
#include "colorchooser.hpp"
#include "colorchooserdialog.hpp"
#include "colorchooserwidget.hpp"
#include "colordialog.hpp"
#include "colordialogbutton.hpp"
#include "columnview.hpp"
#include "columnviewcell.hpp"
#include "columnviewcolumn.hpp"
#include "columnviewrow.hpp"
#include "columnviewsorter.hpp"
#include "combobox.hpp"
#include "comboboxtext.hpp"
#include "constraint.hpp"
#include "constraintguide.hpp"
#include "constraintlayout.hpp"
#include "constraintlayoutchild.hpp"
#include "constrainttarget.hpp"
#include "csslocation.hpp"
#include "cssprovider.hpp"
#include "csssection.hpp"
#include "customfilter.hpp"
#include "customlayout.hpp"
#include "customsorter.hpp"
#include "dialog.hpp"
#include "directorylist.hpp"
#include "dragicon.hpp"
#include "dragsource.hpp"
#include "drawingarea.hpp"
#include "dropcontrollermotion.hpp"
#include "dropdown.hpp"
#include "droptarget.hpp"
#include "droptargetasync.hpp"
#include "editable.hpp"
#include "editablelabel.hpp"
#include "emojichooser.hpp"
#include "entry.hpp"
#include "entrybuffer.hpp"
#include "entrycompletion.hpp"
#include "eventcontroller.hpp"
#include "eventcontrollerfocus.hpp"
#include "eventcontrollerkey.hpp"
#include "eventcontrollerlegacy.hpp"
#include "eventcontrollermotion.hpp"
#include "eventcontrollerscroll.hpp"
#include "everyfilter.hpp"
#include "expander.hpp"
#include "expressionwatch.hpp"
#include "filechooser.hpp"
#include "filechooserdialog.hpp"
#include "filechoosernative.hpp"
#include "filechooserwidget.hpp"
#include "filedialog.hpp"
#include "filefilter.hpp"
#include "filelauncher.hpp"
#include "filter.hpp"
#include "filterlistmodel.hpp"
#include "fixed.hpp"
#include "fixedlayout.hpp"
#include "fixedlayoutchild.hpp"
#include "flattenlistmodel.hpp"
#include "flowbox.hpp"
#include "flowboxchild.hpp"
#include "fontbutton.hpp"
#include "fontchooser.hpp"
#include "fontchooserdialog.hpp"
#include "fontchooserwidget.hpp"
#include "fontdialog.hpp"
#include "fontdialogbutton.hpp"
#include "frame.hpp"
#include "gesture.hpp"
#include "gestureclick.hpp"
#include "gesturedrag.hpp"
#include "gesturelongpress.hpp"
#include "gesturepan.hpp"
#include "gesturerotate.hpp"
#include "gesturesingle.hpp"
#include "gesturestylus.hpp"
#include "gestureswipe.hpp"
#include "gesturezoom.hpp"
#include "glarea.hpp"
#include "grid.hpp"
#include "gridlayout.hpp"
#include "gridlayoutchild.hpp"
#include "gridview.hpp"
#include "headerbar.hpp"
#include "iconpaintable.hpp"
#include "icontheme.hpp"
#include "iconview.hpp"
#include "image.hpp"
#include "imcontext.hpp"
#include "imcontextsimple.hpp"
#include "immulticontext.hpp"
#include "infobar.hpp"
#include "inscription.hpp"
#include "keyvaltrigger.hpp"
#include "label.hpp"
#include "layoutchild.hpp"
#include "layoutmanager.hpp"
#include "levelbar.hpp"
#include "linkbutton.hpp"
#include "listbase.hpp"
#include "listbox.hpp"
#include "listboxrow.hpp"
#include "listheader.hpp"
#include "listitem.hpp"
#include "listitemfactory.hpp"
#include "liststore.hpp"
#include "listview.hpp"
#include "lockbutton.hpp"
#include "maplistmodel.hpp"
#include "mediacontrols.hpp"
#include "mediafile.hpp"
#include "mediastream.hpp"
#include "menubutton.hpp"
#include "messagedialog.hpp"
#include "mnemonicaction.hpp"
#include "mnemonictrigger.hpp"
#include "mountoperation.hpp"
#include "multifilter.hpp"
#include "multiselection.hpp"
#include "multisorter.hpp"
#include "namedaction.hpp"
#include "native.hpp"
#include "nativedialog.hpp"
#include "nevertrigger.hpp"
#include "noselection.hpp"
#include "notebook.hpp"
#include "notebookpage.hpp"
#include "nothingaction.hpp"
#include "numericsorter.hpp"
#include "orientable.hpp"
#include "overlay.hpp"
#include "overlaylayout.hpp"
#include "overlaylayoutchild.hpp"
#include "padactionentry.hpp"
#include "padcontroller.hpp"
#include "pagerange.hpp"
#include "pagesetup.hpp"
#include "pagesetupunixdialog.hpp"
#include "paned.hpp"
#include "papersize.hpp"
#include "passwordentry.hpp"
#include "passwordentrybuffer.hpp"
#include "picture.hpp"
#include "popover.hpp"
#include "popovermenu.hpp"
#include "popovermenubar.hpp"
#include "printcontext.hpp"
#include "printer.hpp"
#include "printjob.hpp"
#include "printoperation.hpp"
#include "printoperationpreview.hpp"
#include "printsettings.hpp"
#include "printunixdialog.hpp"
#include "progressbar.hpp"
#include "range.hpp"
#include "recentdata.hpp"
#include "recentinfo.hpp"
#include "recentmanager.hpp"
#include "requestedsize.hpp"
#include "requisition.hpp"
#include "revealer.hpp"
#include "root.hpp"
#include "scale.hpp"
#include "scalebutton.hpp"
#include "scrollable.hpp"
#include "scrollbar.hpp"
#include "scrolledwindow.hpp"
#include "scrollinfo.hpp"
#include "searchbar.hpp"
#include "searchentry.hpp"
#include "sectionmodel.hpp"
#include "selectionfiltermodel.hpp"
#include "selectionmodel.hpp"
#include "separator.hpp"
#include "settings.hpp"
#include "shortcut.hpp"
#include "shortcutaction.hpp"
#include "shortcutcontroller.hpp"
#include "shortcutlabel.hpp"
#include "shortcutmanager.hpp"
#include "shortcutsgroup.hpp"
#include "shortcutssection.hpp"
#include "shortcutsshortcut.hpp"
#include "shortcutswindow.hpp"
#include "shortcuttrigger.hpp"
#include "signalaction.hpp"
#include "signallistitemfactory.hpp"
#include "singleselection.hpp"
#include "sizegroup.hpp"
#include "slicelistmodel.hpp"
#include "sorter.hpp"
#include "sortlistmodel.hpp"
#include "spinbutton.hpp"
#include "spinner.hpp"
#include "stack.hpp"
#include "stackpage.hpp"
#include "stacksidebar.hpp"
#include "stackswitcher.hpp"
#include "statusbar.hpp"
#include "stringfilter.hpp"
#include "stringlist.hpp"
#include "stringobject.hpp"
#include "stringsorter.hpp"
#include "stylecontext.hpp"
#include "styleprovider.hpp"
#include "switch.hpp"
#include "symbolicpaintable.hpp"
#include "text.hpp"
#include "textbuffer.hpp"
#include "textchildanchor.hpp"
#include "textiter.hpp"
#include "textmark.hpp"
#include "texttag.hpp"
#include "texttagtable.hpp"
#include "textview.hpp"
#include "togglebutton.hpp"
#include "tooltip.hpp"
#include "treedragdest.hpp"
#include "treedragsource.hpp"
#include "treeexpander.hpp"
#include "treeiter.hpp"
#include "treelistmodel.hpp"
#include "treelistrow.hpp"
#include "treelistrowsorter.hpp"
#include "treemodel.hpp"
#include "treemodelfilter.hpp"
#include "treemodelsort.hpp"
#include "treepath.hpp"
#include "treerowreference.hpp"
#include "treeselection.hpp"
#include "treesortable.hpp"
#include "treestore.hpp"
#include "treeview.hpp"
#include "treeviewcolumn.hpp"
#include "urilauncher.hpp"
#include "video.hpp"
#include "viewport.hpp"
#include "volumebutton.hpp"
#include "widget.hpp"
#include "widgetpaintable.hpp"
#include "window.hpp"
#include "windowcontrols.hpp"
#include "windowgroup.hpp"
#include "windowhandle.hpp"

#include "_functions.hpp"


#if defined(__has_include)
#if __has_include(<gtk/gtk_extra_def.hpp>)
#include <gtk/gtk_extra_def.hpp>
#endif
#endif


#if defined(__has_include)
#if __has_include(<gtk/gtk_extra.hpp>)
#include <gtk/gtk_extra.hpp>
#endif
#endif

GI_DISABLE_DEPRECATED_WARN_END

#ifdef GI_INCLUDE_GTK_END
GI_INCLUDE_GTK_END
#endif

#if defined(GI_INLINE) || defined(GI_INCLUDE_IMPL)
#include "gtk_impl.hpp"
#endif

#endif
