// AUTO-GENERATED

#ifndef _GI_PANGO__CONSTANTS_HPP_
#define _GI_PANGO__CONSTANTS_HPP_

namespace gi {

namespace repository {

namespace Pango {

const gint ANALYSIS_FLAG_CENTERED_BASELINE_ = PANGO_ANALYSIS_FLAG_CENTERED_BASELINE;

const gint ANALYSIS_FLAG_IS_ELLIPSIS_ = PANGO_ANALYSIS_FLAG_IS_ELLIPSIS;

const gint ANALYSIS_FLAG_NEED_HYPHEN_ = PANGO_ANALYSIS_FLAG_NEED_HYPHEN;

const guint ATTR_INDEX_FROM_TEXT_BEGINNING_ = PANGO_ATTR_INDEX_FROM_TEXT_BEGINNING;

const guint ATTR_INDEX_TO_TEXT_END_ = PANGO_ATTR_INDEX_TO_TEXT_END;

const PangoGlyph GLYPH_EMPTY_ = PANGO_GLYPH_EMPTY;

const PangoGlyph GLYPH_INVALID_INPUT_ = PANGO_GLYPH_INVALID_INPUT;

const PangoGlyph GLYPH_UNKNOWN_FLAG_ = PANGO_GLYPH_UNKNOWN_FLAG;

const gint SCALE_ = PANGO_SCALE;

const gint VERSION_MAJOR_ = PANGO_VERSION_MAJOR;

const gint VERSION_MICRO_ = PANGO_VERSION_MICRO;

const gint VERSION_MINOR_ = PANGO_VERSION_MINOR;

const gchar VERSION_STRING_[] = PANGO_VERSION_STRING;

} // namespace Pango

} // namespace repository

} // namespace gi

#endif
